import json
import streamlit as st
from supabase import create_client, Client
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

# ============================================================================
# 1. CONFIG & SECRETS
# ============================================================================

st.set_page_config(page_title="ReAG User Study", page_icon="🔬", layout="wide")

EVALUATION_CRITERIA = {
    "DERIVABILITY": "How well does the reasoning trace lead to the final answer? Is the answer explicitly mentioned or clearly derivable?",
    "GRAMMATICAL_CORRECTNESS": "Writing quality: proper grammar, no repetitions, clear language",
    "CONSISTENCY": "Logical coherence: no contradictions, no hallucinations (false claims not in image)"
}

# Load Secrets
try:
    SUPABASE_URL = st.secrets["SUPABASE_URL"]
    SUPABASE_KEY = st.secrets["SUPABASE_KEY"]
    ADMIN_PASSWORD = st.secrets["ADMIN_PASSWORD"]
except FileNotFoundError:
    st.error("Secrets not found. Please configure .streamlit/secrets.toml or Streamlit Cloud Secrets.")
    st.stop()

# Initialize Supabase
@st.cache_resource
def init_supabase() -> Client:
    return create_client(SUPABASE_URL, SUPABASE_KEY)

supabase = init_supabase()

# ============================================================================
# 2. DATABASE FUNCTIONS
# ============================================================================

def save_rating(user_id: str, sample: Dict, ratings: Dict):
    """Upsert rating to Supabase"""
    if any(v is None for v in ratings.values()): return # Skip partials

    data = {
        "user_id": user_id,
        "data_id": sample['data_id'],
        "critique_type": sample['critique_type'],
        "derivability": ratings['derivability'],
        "grammatical_correctness": ratings['grammatical_correctness'],
        "consistency": ratings['consistency'],
        "timestamp": datetime.now().isoformat()
    }
    
    try:
        supabase.table("ratings").upsert(data, on_conflict="user_id, data_id").execute()
    except Exception as e:
        st.error(f"Database Error: {e}")

def get_rating(user_id: str, data_id: str) -> Optional[Dict]:
    """Fetch existing rating"""
    try:
        res = supabase.table("ratings").select("*").eq("user_id", user_id).eq("data_id", data_id).execute()
        if res.data:
            return {k: res.data[0][k] for k in ['derivability', 'grammatical_correctness', 'consistency']}
    except:
        return None

def get_progress(user_id: str) -> int:
    """Get last saved index"""
    try:
        res = supabase.table("user_progress").select("current_index").eq("user_id", user_id).execute()
        return res.data[0]['current_index'] if res.data else 0
    except:
        return 0

def save_progress(user_id: str, index: int):
    """Update progress"""
    try:
        supabase.table("user_progress").upsert({"user_id": user_id, "current_index": index}).execute()
    except Exception as e:
        print(f"Progress Save Error: {e}")

def get_all_results():
    """Admin: Export data"""
    res = supabase.table("ratings").select("*").execute()
    return res.data

# ============================================================================
# 3. UI COMPONENTS
# ============================================================================

def load_data():
    """Load the pre-generated JSON file"""
    # NOTE: Ensure 'user_study_samples.json' is in your GitHub repo
    path = Path("user_study_samples.json")
    if not path.exists():
        st.error("Data file 'user_study_samples.json' not found in repository.")
        st.stop()
    with open(path, "r") as f:
        return json.load(f)

# ============================================================================
# Streamlit UI
# ============================================================================

def show_login():
    """Display the landing page with instructions"""
    st.title("🔬 Reasoning Trace Evaluation Study")
    
    st.markdown("""
    ## Welcome!
    
    Thank you for participating in this user study. Your evaluations will help us verify the quality 
    of automatically generated reasoning traces for visual question answering.
    
    ### What you'll do:
    
    You will evaluate **100 samples** (50 from each dataset). For each sample, you'll see:
    - An **image**
    - A **question** about the image
    - A **reasoning trace** (the model's thinking process)
    - The **final answer** generated by the model
    - Whether the retrieved passage was **relevant** or not
    
    ### Your task:
    
    Rate the **reasoning trace** on three criteria (1-5 scale):
    
    1. **DERIVABILITY**: How well does the reasoning lead to the final answer?
    2. **GRAMMATICAL_CORRECTNESS**: Writing quality, grammar, clarity
    3. **CONSISTENCY**: Logical coherence, no contradictions or hallucinations
    
    ### Important notes:
    
    - You can **pause and resume** anytime using your User ID
    - Use the **Previous/Next** buttons to navigate between samples
    - Your progress is **automatically saved**
    
    ---
    """)
    
    # User ID input
    st.subheader("Enter your User ID to begin:")
    uid = st.text_input(
        "User ID",
        placeholder="e.g., participant_001",
        help="Enter a unique ID to track your progress. You can use this to resume later."
    )
    
    if st.button("Start", type="primary", disabled=not uid):
        st.session_state['user_id'] = uid.strip()
        st.session_state['current_index'] = get_progress(uid.strip())
        st.rerun()

def show_admin():
    with st.sidebar.expander("🔐 Admin"):
        if st.text_input("Password", type="password") == ADMIN_PASSWORD:
            if st.button("Download Data"):
                data = get_all_results()
                st.download_button("Download JSON", json.dumps(data, indent=2), "results.json", "application/json")
                st.success(f"Downloaded {len(data)} records")

def show_evaluation(samples):
    idx = st.session_state['current_index']
    uid = st.session_state['user_id']
    sample = samples[idx]

    # --- Header ---
    st.progress((idx + 1) / len(samples))
    st.caption(f"Sample {idx + 1} / {len(samples)} | User: {uid}")

    # --- Content Layout ---
    col_img, col_txt = st.columns([1, 2])
    
    with col_img:
        st.image(f"data:image/jpeg;base64,{sample['image_b64']}", use_container_width=True)
        st.caption(f"ID: {sample['data_id']}")

    with col_txt:
        st.subheader("Question")
        st.info(sample['question'])
        
        st.subheader("Final Answer")
        st.success(sample['answer'])
        
        with st.expander("📄 Retrieved Context", expanded=False):
            rel = "✅ Relevant" if sample['relevant'] else "❌ Irrelevant"
            st.markdown(f"**Status:** {rel}")
            st.code(sample.get('critique_section', 'N/A'), wrap_lines=True)

    st.subheader("🧠 Reasoning Trace")
    st.markdown(
        f"<div style='background:#f0f2f6; padding:15px; border-radius:5px; white-space:pre-wrap; font-family:monospace;'>{sample['reasoning_trace']}</div>", 
        unsafe_allow_html=True
    )

    st.divider()

    # --- Rating System ---
    existing = get_rating(uid, sample['data_id'])
    ratings = {}
    
    c1, c2, c3 = st.columns(3)
    opts = [1, 2, 3, 4, 5]
    
    for i, (k, desc) in enumerate(EVALUATION_CRITERIA.items()):
        key_lower = k.lower()
        col = [c1, c2, c3][i]
        with col:
            st.markdown(f"**{k.replace('_',' ')}**")
            st.caption(desc)
            # Find default index
            def_idx = None
            if existing and existing.get(key_lower) in opts:
                def_idx = opts.index(existing[key_lower])
            
            ratings[key_lower] = st.radio(
                f"r_{i}", opts, index=def_idx, horizontal=True, key=f"{key_lower}_{idx}", label_visibility="collapsed"
            )

    # --- Navigation ---
    is_complete = all(r is not None for r in ratings.values())
    st.divider()
    b_prev, b_mid, b_next = st.columns([1, 2, 1])

    # 1. Previous Button
    if b_prev.button("⬅️ Previous", disabled=idx==0, use_container_width=True):
        if is_complete:
            save_rating(uid, sample, ratings)
        st.session_state['current_index'] = max(0, idx - 1)
        save_progress(uid, st.session_state['current_index'])
        st.rerun()

    # 2. Save Button
    if b_mid.button("💾 Save (Stay)", use_container_width=True):
        if is_complete:
            save_rating(uid, sample, ratings)
            st.toast("Saved successfully!", icon="✅")
        else:
            st.warning("Please fill all metrics to save this sample.")

    if idx < len(samples) - 1:
        # Change label based on whether metrics are filled
        next_label = "Next ➡️" if is_complete else "Skip ⏩"
        next_type = "primary" if is_complete else "secondary"
        
        if b_next.button(next_label, type=next_type, use_container_width=True):
            if is_complete:
                save_rating(uid, sample, ratings)
            
            st.session_state['current_index'] = idx + 1
            save_progress(uid, idx + 1)
            st.rerun()
    else:
        if b_next.button("Finish 🏁", type="primary", use_container_width=True):
            if is_complete:
                save_rating(uid, sample, ratings)
            st.balloons()
            st.success("Study Complete! You can close this tab.")
            st.stop()

# ============================================================================
# 4. MAIN APP LOGIC
# ============================================================================

if __name__ == "__main__":
    show_admin()
    
    if 'user_id' not in st.session_state:
        show_login()
    else:
        samples = load_data()
        show_evaluation(samples)